# Generated by Django 6.1 on 2026-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_rename_recipoent_recipient"),
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="mailings.recipient", verbose_name="Получатели"
            ),
        ),
    ]
