# Generated by Django 6.1 on 2026-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_mailing_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_disabled",
            field=models.BooleanField(
                default=False, verbose_name="Отключена менеджером"
            ),
        ),
    ]
